[project]
name = "relengjira"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "jira>=3.8.0",
    "mcp[cli]>=1.10.1",
    "requests>=2.32.4",
]